export enum NotificationTemplateType {
  BOOKING_CONFIRMATION = 'BOOKING_CONFIRMATION',
  BOOKING_RESCHEDULE_PROPOSAL = 'BOOKING_RESCHEDULE_PROPOSAL',
  BOOKING_CANCELLATION = 'BOOKING_CANCELLATION',
  ASSIGNMENT_CREATED = 'ASSIGNMENT_CREATED',
  SUBMISSION_FEEDBACK = 'SUBMISSION_FEEDBACK',
  PRACTICE_STREAK = 'PRACTICE_STREAK',
}

export const NOTIFICATION_TEMPLATES = Object.values(NotificationTemplateType);
