name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [unit, e2e]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        if: matrix.suite == 'e2e'
        run: pnpm exec playwright install --with-deps

      - name: Run unit tests
        if: matrix.suite == 'unit'
        run: |
          pnpm test:unit
          pnpm test:contracts

      - name: Run e2e tests
        if: matrix.suite == 'e2e'
        run: pnpm test:e2e
