name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        id: install-deps
        run: pnpm install --frozen-lockfile=false

      - name: Lint
        if: steps.install-deps.outcome == 'success'
        run: pnpm lint

      - name: Typecheck
        if: steps.install-deps.outcome == 'success'
        run: pnpm typecheck

      - name: Test
        if: steps.install-deps.outcome == 'success'
        run: pnpm test

      - name: Build packages
        if: steps.install-deps.outcome == 'success'
        run: pnpm build

      - name: Build API image
        run: docker build -f apps/api/Dockerfile -t soundstudio-api:ci .

      - name: Build Web image
        run: docker build -f apps/web/Dockerfile -t soundstudio-web:ci .

  migrate:
    needs: quality
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Run Prisma migrations
        env:
          DATABASE_URL: postgresql://soundstudio:soundstudio@localhost:5432/soundstudio
        run: pnpm --filter @soundstudio/api run migrate
